Fix 32-bit x86 in-process agent build
Git commit 3c14e5a39bb4fddd added a declaration for
gdb_agent_get_raw_reg to tracepoint.h, and this now caught that the
32-bit x86 implementation has the wrong prototype:

 ../../../src/gdb/gdbserver/linux-i386-ipa.c:103:1: error: conflicting types for ‘gdb_agent_get_raw_reg’
  gdb_agent_get_raw_reg (unsigned char *raw_regs, int regnum)
  ^
 In file included from ../../../src/gdb/gdbserver/linux-i386-ipa.c:24:0:
 ../../../src/gdb/gdbserver/tracepoint.h:168:31: note: previous declaration of ‘gdb_agent_get_raw_reg’ was here
  IP_AGENT_EXPORT_FUNC ULONGEST gdb_agent_get_raw_reg
				^
 make[2]: *** [linux-i386-ipa.o] Error 1

gdb/gdbserver/
2015-03-01  Pedro Alves  <palves@redhat.com>

	* linux-i386-ipa.c (gdb_agent_get_raw_reg): Constify 'raw_regs'
	parameter.